# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-26 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TestDatabase', '0006_auto_20180326_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySpecialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
