# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDatabase', '0007_myspecialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groupe_person', through='TestDatabase.Membership', to='TestDatabase.Person'),
        ),
    ]
