# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestDatabase', '0008_auto_20180327_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='TestDatabase.Membership', to='TestDatabase.Person'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDatabase.Group', unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDatabase.Person', unique=True),
        ),
    ]
